### ISSUE TITLE
Conflicto de codigo

### ISSUE THREAD

**Issue by ClaraPalacios** [mlb0029/GESPRO_PracticaGestionCodigo#4]
Al tratar de modificar el fichero .txt de forma concurrente obtenemos el siguiente problema:

**Comment by ClaraPalacios** [comment]
nos ha descolocado las líneas en las que hemos escrito, ya que habíamos puesto ambos nuestro nombre en la misma línea y nos lo ha eliminado. Además de ello, ha duplicado la línea de la asignatura. 
El fichero final ha sido el siguiente: 

@@ -1,5 +1,12 @@
Componentes del grupo:
<<<<<<< HEAD
Miguel �ngel Le�n Bardav�o

Asignatura: 
Gesti�n de proyectos �gil
\ No newline at end of file
Gesti�n de proyectos �gil
=======
Clara Palacios Rodrigo

Asignatura: 
Gesti�n de Proyectos �gil
>>>>>>> e59bf8da4a2b48b1f5d7257ffa85b3917331de29

**Comment by ClaraPalacios** [comment]
* **LA PATATA CALIENTE**

* Una solución sería resolver el conflicto **subdividirse los cambios** de forma que un compañero modifique una de las partes y el otro otra diferente. 
el fichero muestra información acerca de cómo resolver el conflicto: 
<<<<<<< HEAD
blablabla
esta parte contiene nuestros cambios
=======
blablabla
esta parte contiene los cambios de los compañeros
>>>>>>>[nombre del código de usuario]

se **resuelve el conflicto** de la siguiente forma: 
git reset --hard HEAD
git config merge.conflictstyle diff3
git merge <branch>

**Comment by mlb0029** [comment]
Cuando dos personas modifican a la vez un archivo, y realizan un commit al mismo tiempo ocurre un problema de sincronización:
C:\Users\migue\Documents\GitHub\GESPRO_PracticaGestionCodigo [master ↑]> git push
To https://github.com/mlb0029/GESPRO_PracticaGestionCodigo.git
 ! [rejected]        master -> master (fetch first)
error: failed to push some refs to 'https://github.com/mlb0029/GESPRO_PracticaGestionCodigo.git'
hint: Updates were rejected because the remote contains work that you do
hint: not have locally. This is usually caused by another repository pushing
hint: to the same ref. You may want to first integrate the remote changes
hint: (e.g., 'git pull ...') before pushing again.
hint: See the 'Note about fast-forwards' in 'git push --help' for details.

**Comment by mlb0029** [comment]
C:\Users\migue\Documents\GitHub\GESPRO_PracticaGestionCodigo [master ↑]> git pull
remote: Counting objects: 3, done.
remote: Compressing objects: 100% (2/2), done.
remote: Total 3 (delta 1), reused 3 (delta 1), pack-reused 0
Unpacking objects: 100% (3/3), done.
From https://github.com/mlb0029/GESPRO_PracticaGestionCodigo
   f0f44e4..a3162fa  master     -> origin/master
Auto-merging Conflicto.txt
CONFLICT (content): Merge conflict in Conflicto.txt
Automatic merge failed; fix conflicts and then commit the result.

**Comment by mlb0029** [comment]
C:\Users\migue\Documents\GitHub\GESPRO_PracticaGestionCodigo [master ↕ +0 ~0 -0 !1 | +0 ~0 -0 !1 !]> git status
On branch master
Your branch and 'origin/master' have diverged,
and have 1 and 1 different commits each, respectively.
  (use "git pull" to merge the remote branch into yours)
You have unmerged paths.
  (fix conflicts and run "git commit")
  (use "git merge --abort" to abort the merge)

Unmerged paths:
  (use "git add <file>..." to mark resolution)

        both modified:   Conflicto.txt

no changes added to commit (use "git add" and/or "git commit -a")

**Comment by mlb0029** [comment]
C:\Users\migue\Documents\GitHub\GESPRO_PracticaGestionCodigo [master ↕ +0 ~0 -0 !1 | +0 ~0 -0 !1 !]> git add Conflicto.t
xt
C:\Users\migue\Documents\GitHub\GESPRO_PracticaGestionCodigo [master ↕ +0 ~1 -0 ~]> git commit
[master 7b4da20] Merge remote-tracking branch 'origin/master'
C:\Users\migue\Documents\GitHub\GESPRO_PracticaGestionCodigo [master ↑]> git push
Counting objects: 6, done.
Delta compression using up to 4 threads.
Compressing objects: 100% (6/6), done.
Writing objects: 100% (6/6), 837 bytes | 0 bytes/s, done.
Total 6 (delta 2), reused 0 (delta 0)
remote: Resolving deltas: 100% (2/2), completed with 1 local objects.
To https://github.com/mlb0029/GESPRO_PracticaGestionCodigo.git
   a3162fa..7b4da20  master -> master
